train_data_path:
  1:
    name: 'a'
    scp_path: data/train_clean_100/feats.scp 
    phrase_label: data/train_clean_100/utt2num_frames
    speaker_label: data/train_clean_100/utt2num_frames

dev_data_path:
  1:
    name: 'b'
    scp_path: data/dev_clean/feats.scp 
    phrase_label: data/dev_clean/utt2num_frames
    speaker_label: data/dev_clean/utt2num_frames


